apiVersion: v1
kind: Secret
metadata:
    name: mongo-secret                      # name of secret
    namespace: prof
type: Opaque                                # key-value pairs secret type
data:
    root_password: dG9vcg==                 # toor base64 encoded value
    root_username: cm9vdA==                 # root base64 encoded value
    password: dmVyeXNlY3JldA==              # verysecret base64 encoded value
    username: Z2lj                          # gic base64 encoded value
    replicate_key: cmVwbGljYXZlcnlzZWNyZXQ= # replicaverysecret base64 encoded value
