apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: prof
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: cassandra
  ports:
  - port: 9042
    name: cql
  - port: 7000
    name: intra-node
  - port: 7001
    name: tls-intra-node
  - port: 7199
    name: jmx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: prof
spec:
  serviceName: cassandra
  replicas: 4
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: cassandra
        image: bitnami/cassandra:latest
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "500m"
            memory: 1Gi
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: CASSANDRA_USER
            valueFrom:
              secretKeyRef:
                name: cassandra-secret
                key: username
          - name: CASSANDRA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cassandra-secret
                key: password
          - name: CASSANDRA_SEEDS
            value: "cassandra-0.cassandra.prof.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "GIC"
        volumeMounts:
        - name: cassandra-data
          mountPath: /bitnami
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
      namespace: prof
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi